package pawz.Tournament.Synchronisation;

public enum SynchronisationStatus {
    SYNCHRONISED,
    SYNCHRONISATION_REQUEST_PREPARED,
    SYNCHRONISATION_REQUEST_ACKNOWLEDGED,
    SYNCHRONISATION_REQUEST_SEND,
    AWAITING_SYNCHRONISATION_DATA,
    ALIGNING_SERVICE_THREAD,
    READY_TO_SYNCHRONISE
}
